version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - .:/app/
    environment:
      - TOKEN=${TOKEN}
      - WHITELIST=${WHITELIST}
      - FILTERS=${FILTERS}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - SEARCH_PAGE_SIZE=${SEARCH_PAGE_SIZE}